# NETWORK PASSPHRASE
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

[[CURRENCIES]]
code = "AUDD"
issuer = "GBXCDHFNJ3Q5N2JLYDEA4PT3PX2BSCICG33AIUYR7NBVJLZKFBJHOH7A"
display_dec_precision = 7
description = "AUDD Asset - Official Australian Dollar Token"
desc="Australia's fast, stable, secure fiat-backed stablecoin. Get AUDD today at https://audd-asset.vercel.app"
image="https://audd-asset.vercel.app/logo.png"

[DOCUMENTATION]
ORG_NAME = "AUDD Coin Group"
ORG_URL = "https://audd-asset.vercel.app"
